baseURL = "https://boring-guy.sh/"
languageCode = "en-us"
title = "Boring Guy"
theme = "HugoTeX"
enableEmoji = true
enableInlineShortcodes = true
paginate = 3
footnoteReturnLinkContents = "^"

[author]
  name = "Adil Zouitine"
  #abstract = "Boring Guy"
